<?php

/**
 * BasePrinciples
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $principle_id
 * @property string $name
 * 
 * @method integer    getPrincipleId()  Returns the current record's "principle_id" value
 * @method string     getName()         Returns the current record's "name" value
 * @method Principles setPrincipleId()  Sets the current record's "principle_id" value
 * @method Principles setName()         Sets the current record's "name" value
 * 
 * @package    LifeManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrinciples extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('principles');
        $this->hasColumn('principle_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}