<?php

/**
 * BaseUserTasks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $task_id
 * @property boolean $is_important
 * @property boolean $is_urgent
 * @property integer $task_order
 * @property Tasks $Tasks
 * @property Users $Users
 * 
 * @method integer   getUserId()       Returns the current record's "user_id" value
 * @method integer   getTaskId()       Returns the current record's "task_id" value
 * @method boolean   getIsImportant()  Returns the current record's "is_important" value
 * @method boolean   getIsUrgent()     Returns the current record's "is_urgent" value
 * @method integer   getTaskOrder()    Returns the current record's "task_order" value
 * @method Tasks     getTasks()        Returns the current record's "Tasks" value
 * @method Users     getUsers()        Returns the current record's "Users" value
 * @method UserTasks setUserId()       Sets the current record's "user_id" value
 * @method UserTasks setTaskId()       Sets the current record's "task_id" value
 * @method UserTasks setIsImportant()  Sets the current record's "is_important" value
 * @method UserTasks setIsUrgent()     Sets the current record's "is_urgent" value
 * @method UserTasks setTaskOrder()    Sets the current record's "task_order" value
 * @method UserTasks setTasks()        Sets the current record's "Tasks" value
 * @method UserTasks setUsers()        Sets the current record's "Users" value
 * 
 * @package    LifeManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTasks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_tasks');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_important', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('is_urgent', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('task_order', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tasks', array(
             'local' => 'task_id',
             'foreign' => 'task_id'));

        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}