<?php

/**
 * PrinciplesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrinciplesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrinciplesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Principles');
    }
}