<?php

/**
 * TasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tasks');
    }

    public function getAllTasksByQuad() {
        $tasks = array();
        $tasks['first'] = array();
        $tasks['second'] = array();
        $tasks['third'] = array();
        $tasks['fourth'] = array();

        $query = $this->createQuery('task_by_quad')
                ->orderBy('due_date DESC, created_at DESC');
        $task_results = $query->execute();

        foreach($task_results as $task) {
            if($task->getIsImportant()) {
                if($task->getIsUrgent()) {
                    $tasks['first'][] = $task;
                }
                else {
                    $tasks['second'][] = $task;
                }
            }
            else {
                if($task->getIsUrgent()) {
                    $tasks['third'][] = $task;
                }
                else {
                    $tasks['fourth'][] = $task;
                }
            }
        }


        return $tasks;
    }
}