<?php

/**
 * Tasks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    LifeManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tasks extends BaseTasks
{
    public function getQuadrant() {
        if($this->getUserTasks()->getIsImportant()) {
            if($this->getUserTasks()->getIsUrgent()) {
                return 1;
            }
            else {
                return 2;
            }
        }
        else {
            if($this->getUserTasks()->getIsUrgent()) {
                return 3;
            }
        }
        return 4;
    }
}
