dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=lifemanager'
      username: lifemanager
      password: lifemanager
      attributes:
        tblname_format: lm_%s
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=lifemanager'
      username: lifemanager
      password: lifemanager
      attributes:
        tblname_format: lm_%s