<?php
// auto-generated by sfViewConfigHandler
// date: 2011/02/23 12:45:36
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('jquery.fancybox-1.3.4.css', '', array ());
  $response->addJavascript('jquery.easing-1.3.pack.js', '', array ());
  $response->addJavascript('jquery.fancybox-1.3.4.pack.js', '', array ());
  $response->addJavascript('jquery.mousewheel-3.0.4.pack.js', '', array ());


