Tasks:
  actAs:
    Timestampable: ~
  columns:
    task_id:      { type: integer, notnull: true, primary: true, autoincrement: true }
    name:         { type: string(255), notnull: true }
    due_date:    { type: timestamp, notnull: false, format: Y-m-d H:i:s }
    time_done:    { type: timestamp, notnull: false, format: Y-m-d H:i:s }
    task_order:    { type: integer, notnull: true }
  relations:
    UserTasks:
      local: task_id
      foreign: task_id
      type: one
      foreignType: one

UserTasks:
  actAs:
    Timestampable: ~
  columns:
    user_id:       { type: integer, notnull: true, primary: true, autoincrement: false }
    task_id:       { type: integer, notnull: true, primary: true, autoincrement: false }
    is_important:  { type: boolean, notnull: true, default: false }
    is_urgent:     { type: boolean, notnull: true, default: false }
    task_order:    { type: integer(4), notnull: false }
  relations:
    Tasks:
      local: task_id
      foreign: task_id
      type: one
      foreignType: many
    sfGuardUser:
      local: user_id
      foreign: id
      type: one
      foreignType: many
